var badWordList = {
    "1 man 1 jar": true,
    "1m1j": true,
    "1man1jar": true,
    "2 girls 1 cup": true,
    "2g1c": true,
    "2girls1cup": true,
    "acrotomophile": true,
    "acrotomophilia": true,
    "alabama hot pocket": true,
    "alabama tuna melt": true,
    "alaskan pipeline": true,
    "algophile": true,
    "algophilia": true,
    "anal": true,
    "anal assassin": true,
    "anal astronaut": true,
    "anilingus": true,
    "anus": true,
    "ape shit": true,
    "ape-shit": true,
    "apeshit": true,
    "apotemnophile": true,
    "apotemnophilia": true,
    "arse": true,
    "arse bandit": true,
    "arsehole": true,
    "ass": true,
    "ass bandit": true,
    "asshole": true,
    "auto erotic": true,
    "autoerotic": true,
    "babeland": true,
    "baby batter": true,
    "baby gravy": true,
    "baby juice": true,
    "ball batter": true,
    "ball gag": true,
    "ball gravy": true,
    "ball kicking": true,
    "ball licking": true,
    "ball sack": true,
    "ball sucking": true,
    "ball-gag": true,
    "ball-kicking": true,
    "ball-licking": true,
    "ball-sucking": true,
    "ballcuzi": true,
    "ballgag": true,
    "bang bros": true,
    "bang bus": true,
    "bangbros": true,
    "bangbus": true,
    "bareback": true,
    "barely legal": true,
    "bastard": true,
    "bastinado": true,
    "batty boi": true,
    "batty boy": true,
    "battyboi": true,
    "battyboy": true,
    "bdsm": true,
    "bean flicker": true,
    "bean queen": true,
    "bean-flicker": true,
    "beaner": true,
    "beaners": true,
    "beanflicker": true,
    "beastiality": true,
    "beaver cleaver": true,
    "beaver lips": true,
    "beestiality": true,
    "bellend": true,
    "bellesa": true,
    "bestiality": true,
    "bicon": true,
    "big boobs": true,
    "big breasts": true,
    "big cock": true,
    "big knockers": true,
    "big tits": true,
    "birdlock": true,
    "bitch": true,
    "bitches": true,
    "black cock": true,
    "bloody": true,
    "blow job": true,
    "blow your load": true,
    "blow-job": true,
    "blowjob": true,
    "blue waffle": true,
    "bluewaffle": true,
    "blumpkin": true,
    "bollocks": true,
    "bone smuggler": true,
    "bone-smuggler": true,
    "boner": true,
    "bonesmuggler": true,
    "boob": true,
    "booty buffer": true,
    "booty call": true,
    "booty-buffer": true,
    "boston george": true,
    "breasts": true,
    "brown piper": true,
    "brown shower": true,
    "brown showers": true,
    "brown-piper": true,
    "brownie king": true,
    "brownie queen": true,
    "brownpiper": true,
    "buddha head": true,
    "buddha-head": true,
    "buddhahead": true,
    "bufter": true,
    "bufty": true,
    "bugger": true,
    "bukkake": true,
    "bull shit": true,
    "bull-shit": true,
    "bulldyke": true,
    "bullet vibe": true,
    "bullet vibrator": true,
    "bullshit": true,
    "bum boy": true,
    "bum chum": true,
    "bum driller": true,
    "bum pilot": true,
    "bum pirate": true,
    "bum rider": true,
    "bum robber": true,
    "bum rustler": true,
    "bum-boy": true,
    "bum-chum": true,
    "bum-driller": true,
    "bum-pirate": true,
    "bum-robber": true,
    "bumboy": true,
    "bumchum": true,
    "bumdriller": true,
    "bumhole engineer": true,
    "bumrider": true,
    "bumrobber": true,
    "butt boy": true,
    "butt pilot": true,
    "butt pirate": true,
    "butt rider": true,
    "butt robber": true,
    "butt rustler": true,
    "butt-boy": true,
    "butt-pirate": true,
    "butt-robber": true,
    "buttboy": true,
    "butthole engineer": true,
    "buttrider": true,
    "buttrobber": true,
    "camel jockey": true,
    "camel jockies": true,
    "camel toe": true,
    "cameljockey": true,
    "cameljockies": true,
    "canadian porch swing": true,
    "carpet muncher": true,
    "carpetmuncher": true,
    "cheese eating surrender monkey": true,
    "cheese-eating surrender monkey": true,
    "chi chi man": true,
    "chi-chi man": true,
    "chicken queen": true,
    "china man": true,
    "china men": true,
    "chinaman": true,
    "chinamen": true,
    "ching chong": true,
    "ching-chong": true,
    "chink": true,
    "chinks": true,
    "chinky": true,
    "chocolate rosebud": true,
    "chocolate rosebuds": true,
    "cholerophile": true,
    "cholerophilia": true,
    "christ": true,
    "cialis": true,
    "circle-jerk": true,
    "circlejerk": true,
    "cishet": true,
    "cissie": true,
    "cissy": true,
    "claustrophile": true,
    "claustrophilia": true,
    "cleveland accordion": true,
    "cleveland hot waffle": true,
    "cleveland steamer": true,
    "clit": true,
    "clitoris": true,
    "clover clamp": true,
    "clover clamps": true,
    "clunge": true,
    "cluster fuck": true,
    "cluster-fuck": true,
    "clusterfuck": true,
    "cock": true,
    "cockpipe cosmonaut": true,
    "cockstruction worker": true,
    "coimetrophile": true,
    "coimetrophilia": true,
    "collared": true,
    "collaring": true,
    "coon": true,
    "coons": true,
    "coprolagnia": true,
    "coprophile": true,
    "coprophilia": true,
    "cornhole": true,
    "crafty butcher": true,
    "crap": true,
    "cream-pie": true,
    "creampie": true,
    "cum": true,
    "cum shot": true,
    "cum shots": true,
    "cumming": true,
    "cumshot": true,
    "cumshots": true,
    "cunnilingus": true,
    "cunt": true,
    "cunt boy": true,
    "cunt-boy": true,
    "cuntboy": true,
    "cunts": true,
    "curry muncher": true,
    "curry-muncher": true,
    "currymuncher": true,
    "damn": true,
    "darkey": true,
    "darkie": true,
    "darkies": true,
    "darky": true,
    "date rape": true,
    "daterape": true,
    "ddlg": true,
    "deep throat": true,
    "deep-throat": true,
    "deepthroat": true,
    "dendrophile": true,
    "dendrophilia": true,
    "dick": true,
    "dick girl": true,
    "dick-girl": true,
    "dickgirl": true,
    "dildo": true,
    "dildos": true,
    "dingleberries": true,
    "dingleberry": true,
    "dipsea": true,
    "dirty pillows": true,
    "dirty sanchez": true,
    "dishabiliophile": true,
    "dishabiliophilia": true,
    "dog shit": true,
    "dog style": true,
    "dog-shit": true,
    "doggie style": true,
    "doggie-style": true,
    "doggiestyle": true,
    "doggy style": true,
    "doggy-style": true,
    "doggystyle": true,
    "dogshit": true,
    "dolcett": true,
    "domination": true,
    "dominatrix": true,
    "domme": true,
    "dommes": true,
    "donkey punch": true,
    "donut muncher": true,
    "donut puncher": true,
    "doon coon": true,
    "dooncoon": true,
    "double penetration": true,
    "dp action": true,
    "dry hump": true,
    "dune coon": true,
    "dune-coon": true,
    "dutch rudder": true,
    "dyke": true,
    "dystychiphile": true,
    "dystychiphilia": true,
    "edge play": true,
    "edgeplay": true,
    "ejaculate": true,
    "ejaculated": true,
    "ejaculating": true,
    "ejaculation": true,
    "electro-play": true,
    "electroplay": true,
    "emetophile": true,
    "emetophilia": true,
    "enby": true,
    "eskimo trebuchet": true,
    "eye-tie": true,
    "eyetie": true,
    "fag": true,
    "fag bomb": true,
    "fag-bomb": true,
    "fagbomb": true,
    "faggot": true,
    "fagot": true,
    "felch": true,
    "felching": true,
    "fellating": true,
    "fellatio": true,
    "female squirting": true,
    "figging": true,
    "finger bang": true,
    "fingerbang": true,
    "fingerbanging": true,
    "fingered": true,
    "fingering": true,
    "finocchio": true,
    "finoccio": true,
    "finochio": true,
    "fisted": true,
    "fisting": true,
    "foot job": true,
    "foot-job": true,
    "footjob": true,
    "french rudder": true,
    "frog eater": true,
    "frog-eater": true,
    "frogeater": true,
    "frolic me": true,
    "frolicme": true,
    "frottage": true,
    "frotting": true,
    "fuck": true,
    "fuck-wit": true,
    "fucken": true,
    "fucker": true,
    "fuckers": true,
    "fuckhead": true,
    "fuckheads": true,
    "fuckin": true,
    "fucking": true,
    "fucks": true,
    "fucktard": true,
    "fucktards": true,
    "fuckwad": true,
    "fuckwads": true,
    "fuckwhit": true,
    "fuckwit": true,
    "fuckwits": true,
    "fudge packer": true,
    "fudge-packer": true,
    "fudgepacker": true,
    "futanari": true,
    "g-spot": true,
    "gang bang": true,
    "gangbang": true,
    "gay sex": true,
    "gaysian": true,
    "genitals": true,
    "genitorture": true,
    "gerontophile": true,
    "gerontophilia": true,
    "giant cock": true,
    "gin jockey": true,
    "gin jocky": true,
    "girl on top": true,
    "go-kun": true,
    "goatcx": true,
    "goatse": true,
    "god damn": true,
    "god damned": true,
    "god-damn": true,
    "god-damned": true,
    "goddamn": true,
    "goddamned": true,
    "gokkun": true,
    "golden shower": true,
    "golden showers": true,
    "golliwog": true,
    "gollywog": true,
    "gook": true,
    "gook-eye": true,
    "gookie": true,
    "gooks": true,
    "gooky": true,
    "goregasm": true,
    "gray queen": true,
    "greaseball": true,
    "grey queen": true,
    "grope": true,
    "group sex": true,
    "gym bunny": true,
    "gymbunny": true,
    "hadji": true,
    "haji": true,
    "hajji": true,
    "hand job": true,
    "hand-job": true,
    "handjob": true,
    "heimie": true,
    "hell": true,
    "hermie": true,
    "hickory switch": true,
    "hippophile": true,
    "hippophilia": true,
    "homoerotic": true,
    "honkey": true,
    "honkeys": true,
    "honkies": true,
    "honky": true,
    "horny": true,
    "horse shit": true,
    "horse-shit": true,
    "horseshit": true,
    "hot carl": true,
    "hot richard": true,
    "huge cock": true,
    "humping": true,
    "hymie": true,
    "impact play": true,
    "impact-play": true,
    "incest": true,
    "intercourse": true,
    "jack off": true,
    "jack-off": true,
    "jail bait": true,
    "jailbait": true,
    "jap": true,
    "jelly donut": true,
    "jerk mate": true,
    "jerk off": true,
    "jerk-off": true,
    "jerkmate": true,
    "jesus": true,
    "jesus christ": true,
    "jigaboo": true,
    "jiggerboo": true,
    "jizz": true,
    "juggs": true,
    "jungle bunny": true,
    "junglebunny": true,
    "kennebunkport surprise": true,
    "kentucky klondike": true,
    "kentucky tractor puller": true,
    "kike": true,
    "kinbaku": true,
    "kitty puncher": true,
    "kitty-puncher": true,
    "kittypuncher": true,
    "knobbing": true,
    "kraut": true,
    "krauts": true,
    "kunt": true,
    "kunts": true,
    "kynophile": true,
    "kynophilia": true,
    "lady boy": true,
    "lady-boy": true,
    "ladyboy": true,
    "leather restraint": true,
    "leather straight jacket": true,
    "lemon party": true,
    "lemonparty": true,
    "leningrad steamer": true,
    "lesbo": true,
    "leso": true,
    "lezzie": true,
    "lezzies": true,
    "light in the fedora": true,
    "light in the loafers": true,
    "light in the pants": true,
    "limp wristed": true,
    "limp-wristed": true,
    "literotica": true,
    "lovemaking": true,
    "male squirting": true,
    "male-squirting": true,
    "massive cock": true,
    "masterb8": true,
    "masterbate": true,
    "masturb8": true,
    "masturbate": true,
    "masturbating": true,
    "masturbation": true,
    "mayonnaise monkey": true,
    "mayonnaise monkies": true,
    "mdlb": true,
    "meat masseuse": true,
    "meat spin": true,
    "meatspin": true,
    "menage a trois": true,
    "menage-a-trois": true,
    "menages a trois": true,
    "menages-a-trois": true,
    "menophile": true,
    "menophilia": true,
    "mexican pancake": true,
    "milwaukee blizzard": true,
    "missionary position": true,
    "mississippi birdbath": true,
    "mound of venus": true,
    "mr hands": true,
    "mr. hands": true,
    "mrhands": true,
    "muff diver": true,
    "muff diving": true,
    "muff-diver": true,
    "muffdiver": true,
    "muffdiving": true,
    "muscle mary": true,
    "mvtube": true,
    "nambla": true,
    "necrophile": true,
    "necrophilia": true,
    "negro": true,
    "neo nazi": true,
    "neo-nazi": true,
    "neonazi": true,
    "nig nog": true,
    "nigerian hurricane": true,
    "nigga": true,
    "nigger": true,
    "niggs": true,
    "nignog": true,
    "nimpho": true,
    "nimphomania": true,
    "nimphomaniac": true,
    "nipple": true,
    "nipple clamp": true,
    "nipple clamps": true,
    "nipples": true,
    "nude": true,
    "nudity": true,
    "nutten": true,
    "nympho": true,
    "nymphomania": true,
    "nymphomaniac": true,
    "octopussy": true,
    "oklahomo": true,
    "omorashi": true,
    "one cup two girls": true,
    "one jar one man": true,
    "one man one jar": true,
    "only fans": true,
    "onlyfans": true,
    "orgasm": true,
    "orgasmic": true,
    "orgasms": true,
    "paedo bear": true,
    "paedobear": true,
    "paedophile": true,
    "paedophilia": true,
    "pain slut": true,
    "painslut": true,
    "paki": true,
    "panamanian petting zoo": true,
    "pansy": true,
    "panties": true,
    "parthenophile": true,
    "parthenophilia": true,
    "pedo bear": true,
    "pedobear": true,
    "pedophile": true,
    "pedophilia": true,
    "pegging": true,
    "penis": true,
    "peter puffer": true,
    "peter-puffer": true,
    "peterpuffer": true,
    "petrol sniffer": true,
    "petrol-sniffer": true,
    "petrolsniffer": true,
    "phagophile": true,
    "phagophilia": true,
    "piece of shit": true,
    "pieces of shit": true,
    "pikey": true,
    "pikeys": true,
    "piss off": true,
    "piss pig": true,
    "pissed off": true,
    "pissing": true,
    "pisspig": true,
    "playboy": true,
    "pleasure chest": true,
    "pnigerophile": true,
    "pnigerophilia": true,
    "pnigophile": true,
    "pnigophilia": true,
    "poinephile": true,
    "poinephilia": true,
    "pony boy": true,
    "pony girl": true,
    "pony-boy": true,
    "pony-girl": true,
    "pony-play": true,
    "ponyboy": true,
    "ponygirl": true,
    "ponyplay": true,
    "poof": true,
    "poon": true,
    "poontang": true,
    "poop chute": true,
    "poopchute": true,
    "porn": true,
    "porn hub": true,
    "pornhub": true,
    "porno": true,
    "pornographic": true,
    "pornography": true,
    "pornos": true,
    "potato queen": true,
    "prince albert piercing": true,
    "proctophile": true,
    "proctophilia": true,
    "pubes": true,
    "punani": true,
    "punany": true,
    "pussy": true,
    "pussy puncher": true,
    "pussy-puncher": true,
    "pussypuncher": true,
    "queaf": true,
    "queef": true,
    "quim": true,
    "rag head": true,
    "rag heads": true,
    "raghead": true,
    "ragheads": true,
    "raging boner": true,
    "ramen yarmulke": true,
    "rape": true,
    "raping": true,
    "rapist": true,
    "rectum": true,
    "retard": true,
    "retarded": true,
    "reverse cowgirl": true,
    "rhabdophile": true,
    "rhabdophilia": true,
    "rhypophile": true,
    "rhypophilia": true,
    "rice queen": true,
    "rimjob": true,
    "rimming": true,
    "ring raider": true,
    "ringraider": true,
    "rusty trombone": true,
    "sand nigger": true,
    "sand-nigger": true,
    "sandnigger": true,
    "santorum": true,
    "scatophile": true,
    "scatophilia": true,
    "schlong": true,
    "scissoring": true,
    "semen": true,
    "seplophile": true,
    "seplophilia": true,
    "sex": true,
    "shaved beaver": true,
    "shaved pussy": true,
    "she male": true,
    "she-male": true,
    "sheep shagger": true,
    "sheepshagger": true,
    "shemale": true,
    "shibari": true,
    "shit": true,
    "shit head": true,
    "shithead": true,
    "shitty": true,
    "shlong": true,
    "shota": true,
    "shrimping": true,
    "sissy": true,
    "skeet": true,
    "skittle harvest": true,
    "skittles harvest": true,
    "slant eye": true,
    "slant-eye": true,
    "slanteye": true,
    "snatch": true,
    "snowballing": true,
    "sod off": true,
    "sodding": true,
    "sodomise": true,
    "sodomist": true,
    "sodomize": true,
    "sodomy": true,
    "spastic": true,
    "spearchucker": true,
    "spic": true,
    "spick": true,
    "spicks": true,
    "spics": true,
    "spicy gringo": true,
    "splooge": true,
    "splooge moose": true,
    "spooge": true,
    "spunk": true,
    "strap on": true,
    "strap-on": true,
    "strapon": true,
    "strappado": true,
    "suastika": true,
    "svastika": true,
    "swamp guinea": true,
    "swamp-guinea": true,
    "swastika": true,
    "switch hitter": true,
    "t-girl": true,
    "taphephile": true,
    "taphephilia": true,
    "tea bagged": true,
    "tea bagging": true,
    "tea-bagged": true,
    "tea-bagging": true,
    "tgirl": true,
    "thanatophile": true,
    "thanatophilia": true,
    "threesome": true,
    "throating": true,
    "throbbing boner": true,
    "throbbing cock": true,
    "thumbzilla": true,
    "timber nigger": true,
    "timber-nigger": true,
    "timbernigger": true,
    "tits": true,
    "titties": true,
    "titty": true,
    "topless": true,
    "tosser": true,
    "towel head": true,
    "towel-head": true,
    "towelhead": true,
    "trannie": true,
    "tranny": true,
    "transbian": true,
    "traumatophile": true,
    "traumatophilia": true,
    "tribadism": true,
    "tribbing": true,
    "tub girl": true,
    "tubgirl": true,
    "twat": true,
    "twink": true,
    "two girls one cup": true,
    "urethra play": true,
    "urophile": true,
    "urophilia": true,
    "vagina": true,
    "venus mound": true,
    "viagra": true,
    "vibrator": true,
    "violet wand": true,
    "vorarephile": true,
    "vorarephilia": true,
    "voyeurweb": true,
    "wagon burner": true,
    "wagon-burner": true,
    "wank": true,
    "wanker": true,
    "wax play": true,
    "wax-play": true,
    "wet back": true,
    "wet dream": true,
    "wet-back": true,
    "wetback": true,
    "whigger": true,
    "white power": true,
    "white-power": true,
    "whitepower": true,
    "whore": true,
    "wigga": true,
    "wigger": true,
    "wiitwd": true,
    "wog": true,
    "wogs": true,
    "wolfbagging": true,
    "worldsex": true,
    "wrapping men": true,
    "wrinkled starfish": true,
    "xhamster": true,
    "xnxx": true,
    "xtube": true,
    "xvideos": true,
    "xxx": true,
    "xyrophile": true,
    "xyrophilia": true,
    "yellow shower": true,
    "yellow showers": true,
    "zipper head": true,
    "zipper-head": true,
    "zipperhead": true,
    "zippo cat": true,
    "zippo-cat": true,
    "zippocat": true,
    "zoophile": true,
    "zoophilia": true
}